services:
  db:
    image: postgres:17.6
    environment:
      POSTGRES_USER: wordpress
      POSTGRES_PASSWORD: risa1018
      POSTGRES_DB: wordpress
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    depends_on:
      - db
    build:
      context: .
      args:
        USER_UID: 1000
        WP_PATH: /workspaces/hellopedia/wp
    environment:
      VSCODE_WORKSPACE: /workspaces/hellopedia
    ports:
      - "8080:8080"
      - "80:80"
    volumes:
      - "./..:/workspace"

volumes:
  postgres-data: